### ISSUE TITLE
Memory Error (GC Overhead Limit)

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio/evolv.io#153]
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at java.lang.StringBuilder.toString(Unknown Source)
	at evolv.io.Creature.andifyParents(Creature.java:495)
	at evolv.io.Creature.reproduce(Creature.java:473)
	at evolv.io.CreatureAction$Reproduce.doAction(CreatureAction.java:70)
	at evolv.io.Creature.useBrain(Creature.java:117)
	at evolv.io.Board.iterate(Board.java:375)
	at evolv.io.EvolvioColor.update(EvolvioColor.java:74)
	at evolv.io.EvolvioColor.draw(EvolvioColor.java:67)
	at processing.core.PApplet.handleDraw(PApplet.java:2418)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```

**Comment by PRabahy** [comment]
How many creatures did you have and how long had your simulation been running?

**Comment by NateUniAccount** [comment]
I believe that's nothing to do with the andifyParents() method and that it's just the point where the jvm happened to run out of available memory. It sounds like some references are being held every iteration or for every new creature.

**Comment by NateUniAccount** [comment]
It needs a look over with jvisualvm really

**Comment by UnknownEvil** [comment]
I've edited the post to add the most recent version, It's happened every time I've run it overnight.

**Comment by PRabahy** [comment]
We can probably work on optimizing memory usage, but I haven't found any actual leaks in the bit of benchmarking I was doing.

How much memory do you have? https://stackoverflow.com/questions/6452765/how-to-increase-heap-size-of-jvm shows how to increase the amount of space that Java can use.

**Comment by UnknownEvil** [comment]
Alright, I'll see if I can increase it. 6GB RAM PC.
I don't know how much is allocated.
