### ISSUE TITLE
sun.dc.pr.PRError at 6cd026c9d2479513228f91c141d214a168f4f84d

### ISSUE THREAD

**Issue by PRabahy** [evolvio/evolv.io#159]
sun.dc.pr.PRError: setPenT4: invalid pen transformation (singular)
	at sun.dc.pr.PathStroker.setPenT4(Native Method)
	at sun.dc.pr.Rasterizer.setPenT4(Unknown Source)
	at sun.dc.DuctusRenderingEngine.getAATileGenerator(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
	at sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
	at sun.java2d.SunGraphics2D.draw(Unknown Source)
	at processing.awt.PGraphicsJava2D.drawShape(PGraphicsJava2D.java:1364)
	at processing.awt.PGraphicsJava2D.ellipseImpl(PGraphicsJava2D.java:1257)
	at processing.core.PGraphics.ellipse(PGraphics.java:2808)
	at processing.core.PApplet.ellipse(PApplet.java:11630)
	at evolv.io.Creature.drawMouth(Creature.java:151)
	at evolv.io.Creature.drawSoftBody(Creature.java:126)
	at evolv.io.Board.drawBoard(Board.java:127)
	at evolv.io.EvolvioColor.render(EvolvioColor.java:132)
	at evolv.io.EvolvioColor.draw(EvolvioColor.java:87)
	at processing.core.PApplet.handleDraw(PApplet.java:2418)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by PRabahy** [comment]
I got this after I let it run overnight at 256x with rendering disabled. In the morning I enabled rendering and clicked on the largest creature. A couple of seconds later it froze with that exception.

**Comment by NateUniAccount** [comment]
Looks like it's the same error as in #81 with the same stack trace

**Comment by NateUniAccount** [comment]
Closing this as it looks like the same bug as #81
