### ISSUE TITLE
Ellipse draw error

### ISSUE THREAD

**Issue by kodomazer** [evolvio/evolv.io#81]
I haven't changed any of the code in the stack trace, so I assume this is a problem that exists within the project as a whole.  Attached are the stack trace for the problem as well as a screenshot of the screen state when it crashed.  

The commit hash is `6d97d60e121ef415183816d3c2d403b159369cdb` and I'm running it with 64-bit eclipse.

This problem is what cut my last run of the simulation at just over 600 years.  I'll post a gif of this run somewhere so everyone can take a look at how its going.

Stack Trace:
`No glyph found for the ? (\uFFFD) character
sun.dc.pr.PRError: setPenT4: invalid pen transformation (singular)
	at sun.dc.pr.PathStroker.setPenT4(Native Method)
	at sun.dc.pr.Rasterizer.setPenT4(Unknown Source)
	at sun.dc.DuctusRenderingEngine.getAATileGenerator(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
	at sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
	at sun.java2d.SunGraphics2D.draw(Unknown Source)
	at processing.awt.PGraphicsJava2D.drawShape(PGraphicsJava2D.java:1364)
	at processing.awt.PGraphicsJava2D.ellipseImpl(PGraphicsJava2D.java:1257)
	at processing.core.PGraphics.ellipse(PGraphics.java:2808)
	at processing.core.PApplet.ellipse(PApplet.java:11630)
	at evolv.io.Creature.drawMouth(Creature.java:217)
	at evolv.io.Creature.drawSoftBody(Creature.java:163)
	at evolv.io.Board.drawBoard(Board.java:148)
	at evolv.io.EvolvioColor.draw(EvolvioColor.java:107)
	at processing.core.PApplet.handleDraw(PApplet.java:2418)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)`

Last drawn screen:
![image](https://cloud.githubusercontent.com/assets/9631305/21876031/e77a864a-d834-11e6-8008-becaab1f460b.png)

**Comment by PRabahy** [comment]
I did a little digging and it seems that the call to Creature.drawMouth() is somehow causing a lower level java library to try to display \uFFFD ("Replacement Character"). I traced the code in eclipse all the way thru the entire processing portion of the stack and none of that tried to display that character. The only 2 options I see are to generate a new vlw file with the entire unicode character set or just catch and throw away the exception. I'm not really happy about either option.

**Comment by PRabahy** [comment]
I just posted a possible fix. It makes some of the text look ugly, but IMO that can be cleaned up later. Does this fix the issue for you?

**Comment by kodomazer** [comment]
Has anyone else been having this issue?  If it's just me, I think we can leave it for now, I just needed to run it to make sure evolution works, and it doesn't actively stop me from doing that.

**Comment by PRabahy** [comment]
I have run several simulations out past 1000 years and haven't seen that error myself.

**Comment by kodomazer** [comment]
Okay, I was running the sim and I noticed that I got some console log errors that didn't break the runtime:

`No glyph found for the ? (\u221E) character
No glyph found for the ? (\uFFFD) character`

Note that I am still running on the same commit hash as before.

**Comment by 10carfernandez** [comment]
It looks like the problem is that at some point, the creature's values (hue, mouthHue, px, py, etc.) get set to NaN. 

I set a break point in Creature.java around line 322 where it says:

> this.evolvioColor.text("X: " + EvolvioColor.nf((float) selectedCreature.px, 0, 2), 10, 350);

and then clicked on an invisible creature. What I saw was that the value for selectedCreature.px, as well as some of the other values, where set to "NaN." 

The values set to NaN were the following: 
energy
hue
mouthHue
px
py
rotation
vr
vx
vy

From Softbody, I think the reason saturation and brightness don't appear as NaN is because they get set equal to 1 at the end of the reproduce() method in Creature. 

What throws me off, though, is that this seems to happen to the parents, and not the babies....

**Comment by kodomazer** [comment]
I think you meant to put that in #52 , this issue is with the program crashing.

**Comment by 10carfernandez** [comment]
Whoops. Let me delete this post and re-post it in the appropriate issue then.

**Comment by NateUniAccount** [comment]
It might be an idea to put a try catch block around where it's drawing the ellipse in Creature drawMouth and put some debugging in. It might be a zero or negative ellipse width or height

**Comment by NateUniAccount** [comment]
Another instance of this bug from @PRabahy 

sun.dc.pr.PRError: setPenT4: invalid pen transformation (singular)
at sun.dc.pr.PathStroker.setPenT4(Native Method)
at sun.dc.pr.Rasterizer.setPenT4(Unknown Source)
at sun.dc.DuctusRenderingEngine.getAATileGenerator(Unknown Source)
at sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
at sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
at sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
at sun.java2d.SunGraphics2D.draw(Unknown Source)
at processing.awt.PGraphicsJava2D.drawShape(PGraphicsJava2D.java:1364)
at processing.awt.PGraphicsJava2D.ellipseImpl(PGraphicsJava2D.java:1257)
at processing.core.PGraphics.ellipse(PGraphics.java:2808)
at processing.core.PApplet.ellipse(PApplet.java:11630)
at evolv.io.Creature.drawMouth(Creature.java:151)
at evolv.io.Creature.drawSoftBody(Creature.java:126)
at evolv.io.Board.drawBoard(Board.java:127)
at evolv.io.EvolvioColor.render(EvolvioColor.java:132)
at evolv.io.EvolvioColor.draw(EvolvioColor.java:87)
at processing.core.PApplet.handleDraw(PApplet.java:2418)
at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by 10carfernandez** [comment]
I had already found a fix for this. I've run simulations for over 70,000 years now and never ran into that problem again. I thought I had referenced this in the issues section. I'll do that later. 

The issue has to do with the value NaN being passed in some of the methods that take in numeric values. Eventually, the NaN value propagates to other objects and methods, and eventually gets passed into the draw method, which causes this issue. 

One approach that can be taken is to truncate the values of the axon weights, and check that the outputs of the last layer aren't NaN. 

For example, sometimes the tiles become invisible when a creature vomits a value of NaN because you're adding NaN to the amount of yums. Then, when another creature passes by and its eating value is greater than 0, NaN yums will be added to the creature's energy, causing its size to become NaN, and that neuron will pass NaN to the next neurons, propagating NaN throughout the whole brain.

**Comment by kodomazer** [comment]
Note that #160 was made in an attempt to fix this problem (which I believe it did, though I don't remember testing it) which is newer than the referenced #159 , so the actual posting time in order to cross reference the issues is slightly misleading.

**Comment by UnknownEvil** [comment]
Perhaps the bug still exists, with the changes that were meant to fix it, all that happens is the font was loaded differently, the reason the unavailable character bug happens is because it's a character that gets requested (somehow, I've only looked at it for a moment), in almost every font. \uFFF0 simply does not exist in most fonts. Somehow making sure that doesn't happen would be a quick fix. But, this is a "perhaps" so it could be fixed, I haven't done enough testing.

**Comment by 10carfernandez** [comment]
I think that looking for a font that "works" is only treating the symptom and not providing the cure for this problem. A creature's color, for example, will not depend on the font being used. So even if we find a font that works, the creatures will still turn black and the values will be some weird non-numeric characters.

**Comment by UnknownEvil** [comment]
That's not what I was saying, I said avoid that happening at all, not change the font, of course that's an awful idea and solves nothing, I've been looking into it, but I can't find the reason it's happening, NaN value perhaps, like you said a while ago.

**Comment by 10carfernandez** [comment]
It probably is that, since I've been able to run simulations for over 70,000 years now. I think I ran it for over 150,000 years once too.

**Comment by UnknownEvil** [comment]
At this point, I don't think it's 100% guaranteed a NaN value, I know the bug happens reliably if you try to divide by the getFoodLevel() {Sometimes returns a very small number resulting in infinity, which propagates throughout the system}

**Comment by 10carfernandez** [comment]
Probably not 100% guaranteed. In fact, I know that that's not the only thing that causes it. But the fix that I wrote did make the sim run at least over 100 times longer than it previously could (probably longer, but I haven't tried running it for any longer). 

I think what you're mentioning is one very small part of it. I remember finding a few other situations in which extreme non-numeric values (so NaN or Inf) would be created. But in the vast majority of cases, it is caused by the values of the weights becoming extremely polarized. Hence, why I haven't seen the issue appear in my solution since the fix I made, which involved changing the way axon weights mutate.

**Comment by UnknownEvil** [comment]
Hopefully eventually we can find the source(s) of the bug, and get it fixed.

**Comment by Grimtin10** [comment]
For me it appeared the it was a radius of 0 that broke it, so I changed ellipse(0.6*scaleUp,0,0.37*scaleUp,0.37*scaleUp); to 
if(radius>0){
  ellipse(0.6*scaleUp,0,0.37*scaleUp,0.37*scaleUp);
}

**Comment by UnknownEvil** [comment]
There is probably a better method like preventing the creatures from ever reaching a radius of 0
@Grimtin10 there is are new projects (which are all basically scratch, except javascript) at https://github.com/evolvio4all/
